// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKAeuCpTAjNy106nOU8gmvDgpA3lJ6FY',
    appId: '1:232561086905:web:dc637cbab66ece85266668',
    messagingSenderId: '232561086905',
    projectId: 'fitnessfinal-3e6fa',
    authDomain: 'fitnessfinal-3e6fa.firebaseapp.com',
    storageBucket: 'fitnessfinal-3e6fa.appspot.com',
    measurementId: 'G-DS9Q4XZVJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAsTRvSb-6apY-WHytLI1wb-OpmXl-K5c',
    appId: '1:232561086905:android:67cf068730bac947266668',
    messagingSenderId: '232561086905',
    projectId: 'fitnessfinal-3e6fa',
    storageBucket: 'fitnessfinal-3e6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsP7879V54sm3N__VNQMMlZYut2FlCnCc',
    appId: '1:232561086905:ios:a9d88ecf30d4937d266668',
    messagingSenderId: '232561086905',
    projectId: 'fitnessfinal-3e6fa',
    storageBucket: 'fitnessfinal-3e6fa.appspot.com',
    iosBundleId: 'com.example.fitnessFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsP7879V54sm3N__VNQMMlZYut2FlCnCc',
    appId: '1:232561086905:ios:5a5839f3e3f73262266668',
    messagingSenderId: '232561086905',
    projectId: 'fitnessfinal-3e6fa',
    storageBucket: 'fitnessfinal-3e6fa.appspot.com',
    iosBundleId: 'com.yaksi.fitnessFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHKAeuCpTAjNy106nOU8gmvDgpA3lJ6FY',
    appId: '1:232561086905:web:5e59bce9806e14f5266668',
    messagingSenderId: '232561086905',
    projectId: 'fitnessfinal-3e6fa',
    authDomain: 'fitnessfinal-3e6fa.firebaseapp.com',
    storageBucket: 'fitnessfinal-3e6fa.appspot.com',
    measurementId: 'G-3FLM1YM7PJ',
  );
}
